default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres


development:
  <<: *default
  database: rails_app_development
  username: postgres
  password: ''

test:
  <<: *default
  database: rails_app_test
  username: postgres
  password: ''

production:
  <<: *default
  database: rails_app_production
  username: postgres
  password: '123456'
