# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55b4f64180754f4ea2b76663e664e270e793907c44287fb166148eb978c9b6e141a79281690a798cbad60a88d3b6b7b271bed231a88001d4d0aa9238b41c708

test:
  secret_key_base: c3c873d2a3d7de81530df6cafb072cb14f4a08fa418d0670f9554358fae6185495cdf82e8d406fe46e428aa722e6355fa9e65d1f69307eec2fe0ad0aa87e62f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
